language: go

go:
  - "1.14.7"  # Golang 1.14.7

# Specify which branches to build using a safelist

branches:
  only:
    - hugo

install:
  # Install hugo
  - wget https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_extended_0.74.3_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  # Remove .deb to avoid being added to git
  - sudo rm hugo*.deb
  # install themes
  - git clone https://github.com/xianmin/hugo-theme-jane.git --depth=1 themes/jane

before_script:
  # Important for travis-ci
  # Travis-ci add --depth when clone by default, causing fetch origin/other-branch to fail
  - git fetch origin +refs/heads/gh-pages:refs/remotes/origin/gh-pages

script:  

   # Run publish script

  - . publish_to_ghpages.sh

# after_script:


env:
 global:
   # Github Pages
   - GH_REF: github.com/skykui/skykui.github.io.git

deploy:
  provider: pages 
  cleanup: false 
  local_dir: public 
  target_branch: gh-pages 
  github_token: $GITHUB_TOKEN 
  # fqdn:  # domain name
  keep_history: true 
  branch: hugo 