language: go

go:
  - "1.14.7"  # 指定Golang 1.14.7

# Specify which branches to build using a safelist
# 分支白名单限制：只有 master 分支的提交才会触发构建
branches:
  only:
    - hugo

install:
  # 安装最新的hugo
  - wget https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_extended_0.74.3_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  # 安装主题
  - git clone https://github.com/xianmin/hugo-theme-jane.git --depth=1 themes/jane

script:
  # 运行hugo命令
  - hugo

after_script:
  # 部署
  - . publish_to_ghpages.sh
  # - cd ./public
  # - git init
  # - git config user.name "[你的名字]"
  # - git config user.email "[你的邮箱]"
  # - git add .
  # - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # # Github Pages
  # - git push --force --quiet "https://$GITHUB_TOKEN@${GH_REF}" master:master
  # # Github Pages
  # - git push --quiet "https://$GITHUB_TOKEN@${GH_REF}" master:master --tags

env:
 global:
   # Github Pages
   - GH_REF: https://github.com/skykui/skykui.github.io.git

deploy:
  provider: pages # 重要，指定这是一份github pages的部署配置
  skip-cleanup: true # 重要，不能省略
  local-dir: public # 静态站点文件所在目录
  # target-branch: master # 要将静态站点文件发布到哪个分支
  github-token: $GITHUB_TOKEN # 重要，$GITHUB_TOKEN是变量，需要在GitHub上申请、再到配置到Travis
  # fqdn:  # 如果是自定义域名，此处要填
  keep-history: true # 是否保持target-branch分支的提交记录
  on:
    branch: gh-pages # 博客源码的分支